#!/bin/bash
# Vagrant sfdev provision script, to be run in guest when creating basebox
set -xueo pipefail

# Duplicate output to a log file
exec &> >(tee "$(mktemp --tmpdir "provision-$(date +"%F-%H%M%S")-XXXXXXXXXX.log")")

# Helper method to avoid failing from a network hiccup during provision
function tryharderto() {
  i=0
  until "$@"; do
    ((++i <= 3))
    echo >&2 "Retrying ${i}"
    sleep 2m
  done
}

# Vagrant Ubuntu setup
# --------------------

# Turn off applying automatic updates, so that a user won't turn off the
# machine during updates, which may make a mess.
sudo tee /etc/apt/apt.conf.d/90disable-auto-updates >/dev/null <<END
APT::Periodic::Unattended-Upgrade "0";
END

# Apply all available updates
tryharderto sudo apt-get update
tryharderto sudo apt-get --assume-yes upgrade
tryharderto sudo apt-get --assume-yes dist-upgrade

# Swap shouldn't be necessary and may cause unnecessary churn when backing up the guest
# image. Disable and delete the swapfile.
sudo swapoff --all &&
  sudo perl -ni -e 'print unless /swapfile/' /etc/fstab &&
  sudo rm -vf /swapfile

# Don't prompt for OS upgrade to newer release
sudo perl -pi -e 's/Prompt=lts/Prompt=never/' /etc/update-manager/release-upgrades

# sshd security settings
sudo mkdir --parents /etc/ssh/sshd_config.d
sudo tee /etc/ssh/sshd_config.d/no-password-authentication-or-root.conf >/dev/null <<END
PasswordAuthentication no
PermitRootLogin no
END

# Passwordless sudo
sudo tee /etc/sudoers.d/passwordless >/dev/null <<<'vagrant ALL=(ALL) NOPASSWD: ALL'

sudo tee /etc/sudoers.d/stars >/dev/null <<END
# Show stars when typing sudo password.
Defaults pwfeedback
END
sudo chmod 0400 /etc/sudoers.d/stars

sudo tee /etc/default/grub.d/90-show-boot-output.cfg >/dev/null <<END
# Reveal boot information for investigating problems, rather than being pretty.
GRUB_CMDLINE_LINUX_DEFAULT="" # no quiet splash
GRUB_TIMEOUT_STYLE="menu"
GRUB_TIMEOUT="2"
END

# Turn off error reporting from hogging memory
sudo perl -pi -e 's/enabled=1/enabled=0/' /etc/default/apport

# Make vagrant accessible via ssh
tryharderto sudo apt-get --assume-yes install openssh-server

# Install initial vagrant login key.
cd "$(mktemp -d)"
wget 'https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub'
sha512sum -c <<< \
  'f1891f744e3619e19f737d8f2742a6ffe12681fcd6878ae5ed804556bcaa7762fdbd750ed653ee3c6cfb4bb159f860187446460102100f35685c32444c2300ad  vagrant.pub'
mkdir --parents ~/.ssh
chmod 0700 ~/.ssh
mv vagrant.pub ~/.ssh/authorized_keys
chmod 0600 ~/.ssh/authorized_keys

# Prepare for ssh host keys to be re-generated by users
sudo tee /root/generate-missing-ssh-host-keys >/dev/null <<END
#!/bin/bash
# Generate SSH host keys if not present
test -f /etc/ssh/ssh_host_rsa_key || ssh-keygen -A
END
sudo chmod +x /root/generate-missing-ssh-host-keys
sudo tee /etc/systemd/system/generate-missing-ssh-host-keys.service >/dev/null <<END
[Unit]
Description=generate-missing-ssh-host-keys

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/root/generate-missing-ssh-host-keys

[Install]
WantedBy=multi-user.target
END
sudo systemctl enable generate-missing-ssh-host-keys

# Don't blank or lock VM screen
kwriteconfig5 --file kscreenlockerrc --group Daemon --key Autolock false
kwriteconfig5 --file kscreenlockerrc --group Daemon --key Timeout 0
kwriteconfig5 --file kscreenlockerrc --group Daemon --key LockOnResume false
kwriteconfig5 --file powermanagementprofilesrc --group DPMSControl --key idleTime \\-1
kwriteconfig5 --file powermanagementprofilesrc --group DPMSControl --key lockBeforeTurnOff 0

# Adjust bash prompt
# Use colour
perl -pi -e '/#force/ and s/^#//' ~/.bashrc
# Place $ on next line (when not already preceded by \n)
perl -pi -e '/PS1/ and s/(?<!\\n)\\\$ /\\n\\\$ /' ~/.bashrc
# Show exit code
perl -pi -e '/PS1/ and s/@/\$?/' ~/.bashrc

# Dark theme
lookandfeeltool --apply org.kde.breezedark.desktop

tryharderto sudo apt-get --assume-yes install plasma-discover-backend-flatpak kde-config-flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Steady cursor, not blinking
mkdir --parents ~/.qt
tee --append ~/.qt/qtrc >/dev/null <<END
[General]
cursorFlashTime=0
END
mkdir --parents ~/.config
tee --append ~/.config/kdeglobals >/dev/null <<END
[KDE]
CursorBlinkRate=0
END
gsettings set org.gnome.desktop.interface cursor-blink false

# Don't report developer or tester usage to analytics
mkdir --parents ~/.config/environment.d
tee --append ~/.config/environment.d/sil-no-analytics.conf >/dev/null <<END
FEEDBACK=false
WESAY_TRACK_AS_DEVELOPER=1
END

# Record some base box version info, to help with diagnosis
tee ~/machine-info.txt >/dev/null <<END
Vagrant base box information
Name: sfdev
Version:
Creation date: $(date -I)
Installed from:
Notes:
END

# Keyboarding
# Turn off fcitx5 before updating config by hand. More reliable than `fcitx5-remote -r`.
pkill fcitx5
sleep 2s
tee ~/.config/fcitx5/profile >/dev/null <<END
[Groups/0]
# Group Name
Name=Default
# Layout
Default Layout=us
# Default Input Method
DefaultIM=keyboard-us

[Groups/0/Items/0]
# Name
Name=keyboard-us
# Layout
Layout=

[Groups/0/Items/1]
# Name
Name=keyboard-th
# Layout
Layout=

[Groups/0/Items/2]
# Name
Name=keyboard-ru
# Layout
Layout=

[Groups/0/Items/3]
# Name
Name=pinyin
# Layout
Layout=

[Groups/0/Items/4]
# Name
Name=keyboard-il
# Layout
Layout=

[Groups/0/Items/5]
# Name
Name=keyboard-us-dvorak
# Layout
Layout=

[GroupOrder]
0=Default
END

# Set unique background
IMAGE_CODE="RbN8pwcYCyM" # Hedgehog for Ubuntu 24.04
mkdir --parents ~/.local/share/backgrounds
wget -O "${HOME}/.local/share/backgrounds/${IMAGE_CODE}-unsplash.jpg" \
  "https://unsplash.com/photos/${IMAGE_CODE}/download?force=true"
# Desktop
WALLPAPER_URI="file:///home/vagrant/.local/share/backgrounds/${IMAGE_CODE}-unsplash.jpg"
kwriteconfig5 --file plasma-org.kde.plasma.desktop-appletsrc \
  --group 'Containments' --group '1' --group 'Wallpaper' --group 'org.kde.image' --group 'General' \
  --key Image "${WALLPAPER_URI}"
# Lock screen
kwriteconfig5 --file kscreenlockerrc \
  --group Greeter --group Wallpaper --group org.kde.image --group General \
  --key Image "${WALLPAPER_URI}"

# Configure panel
# ------------------

# Show CPU and memory in system monitor
PANEL_CONFIG="plasma-org.kde.plasma.desktop-appletsrc"
SYSMON_ID="24"
PANEL_CONTAINMENT_ID="2"
kwriteconfig5 --file "${PANEL_CONFIG}" \
  --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
  --group "${SYSMON_ID}" --key immutability 1
kwriteconfig5 --file "${PANEL_CONFIG}" \
  --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
  --group "${SYSMON_ID}" --key plugin org.kde.plasma.systemmonitor
kwriteconfig5 --file "${PANEL_CONFIG}" \
  --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
  --group "${SYSMON_ID}" --group 'Configuration' --key CurrentPreset org.kde.plasma.systemmonitor
kwriteconfig5 --file "${PANEL_CONFIG}" \
  --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
  --group "${SYSMON_ID}" --group 'Configuration' --key PreloadWeight 100
kwriteconfig5 --file "${PANEL_CONFIG}" \
  --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
  --group "${SYSMON_ID}" --group 'Configuration' --group 'Appearance' \
  --key chartFace org.kde.ksysguard.barchart
kwriteconfig5 --file "${PANEL_CONFIG}" \
  --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
  --group "${SYSMON_ID}" --group 'Configuration' --group 'Appearance' \
  --key title 'System Monitor'
kwriteconfig5 --file "${PANEL_CONFIG}" \
  --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
  --group "${SYSMON_ID}" --group 'Configuration' --group 'Appearance' \
  --key updateRateLimit 60000
# Blue
kwriteconfig5 --file "${PANEL_CONFIG}" \
   --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
   --group "${SYSMON_ID}" --group 'Configuration' --group 'SensorColors' \
   --key 'cpu/all/usage' '61,174,233'
# Green
kwriteconfig5 --file "${PANEL_CONFIG}" \
   --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
   --group "${SYSMON_ID}" --group 'Configuration' --group 'SensorColors' \
   --key 'memory/physical/usedPercent' '0,170,127'
kwriteconfig5 --file "${PANEL_CONFIG}" \
   --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
   --group "${SYSMON_ID}" --group 'Configuration' --group 'SensorLabels' \
   --key 'cpu/all/usage' 'CPU %'
kwriteconfig5 --file "${PANEL_CONFIG}" \
   --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
   --group "${SYSMON_ID}" --group 'Configuration' --group 'SensorLabels' \
   --key 'memory/physical/usedPercent' 'Mem %'
kwriteconfig5 --file "${PANEL_CONFIG}" \
  --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
  --group "${SYSMON_ID}" --group 'Configuration' --group 'Sensors' \
  --key highPrioritySensorIds '["cpu/all/usage","memory/physical/usedPercent"]'

KICKOFF_ID=3 # Start button

# Use more recognizable applications menu icon
kwriteconfig5 --file "${PANEL_CONFIG}" \
  --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" --group 'Applets' \
  --group "${KICKOFF_ID}" --group 'Configuration' --group 'General' --key icon "show-grid"

# Panel widgets
{
PAGER=4 # Workspace grid
ICONTASKS=5 # Task bar
SEPARATOR=6
MONITOR=24 # System monitor
SYSTEMTRAY=7
CLOCK=19
MINIMIZEALL=20 # Skipping
kwriteconfig5 --file "${PANEL_CONFIG}" --group 'Containments' --group "${PANEL_CONTAINMENT_ID}" \
  --group 'General' --key AppletOrder \
  "${KICKOFF_ID};${PAGER};${ICONTASKS};${SEPARATOR};${MONITOR};${SYSTEMTRAY};${CLOCK}"
}

# Configure desktop for development
# ---------------------------------

# Tools

tryharderto sudo apt-get --assume-yes install \
  ack \
  ripgrep \
  curl \
  flatpak \
  net-tools \
  tig \
  vim \
  wget \
  glances \
  inotify-tools \
  synaptic \
  dconf-cli \
  git-gui \
  git-cola \
  jq \
  byobu \
  mercurial \
  meld \
  kdiff3 \
  ;

# For now, still use apt to install chromium-browser, to set up /usr/bin/chromium-browser executable.
tryharderto sudo apt-get --assume-yes install chromium-browser chromium-browser-l10n

sudo snap install chromium
# Add MP3 support to Chromium
sudo snap install chromium-ffmpeg

sudo snap install firefox

# Ideally, application specific signing keys would be stored in
# /usr/share/keyrings/, with the repo source specifying signed-by it. But Chrome
# and Edge have daily cron jobs that re-establish their own settings, even
# putting the key in the globally trusted area. And Code gives an error during
# installation if its key isn't in the globally trusted area. Not fighting with
# it.

# Chrome
cd $(mktemp -d)
curl --silent --location --fail --show-error \
  https://dl.google.com/linux/linux_signing_key.pub |
  gpg --dearmor >google-chrome.gpg
sudo install --owner root --group root --mode 644 \
  google-chrome.gpg /etc/apt/trusted.gpg.d/
sudo tee /etc/apt/sources.list.d/google-chrome.list >/dev/null <<< \
  "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
tryharderto sudo apt-get update
tryharderto sudo apt-get --assume-yes install google-chrome-stable

# Edge
cd $(mktemp -d)
curl --silent --location --fail --show-error \
  https://packages.microsoft.com/keys/microsoft.asc |
  gpg --dearmor >microsoft.gpg
sudo install --owner root --group root --mode 644 \
  microsoft.gpg /etc/apt/trusted.gpg.d/
sudo tee /etc/apt/sources.list.d/microsoft-edge.list >/dev/null <<< \
  "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
tryharderto sudo apt-get update
tryharderto sudo apt-get --assume-yes install microsoft-edge-stable

# Brave
cd $(mktemp -d)
curl --silent --location --fail --show-error \
  --output brave-browser-archive-keyring.gpg \
  https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
sudo install --owner root --group root --mode 644 \
  brave-browser-archive-keyring.gpg /etc/apt/keyrings/
sudo tee /etc/apt/sources.list.d/brave-browser-release.sources >/dev/null <<-END
	Types: deb
	URIs: https://brave-browser-apt-release.s3.brave.com/
	Suites: stable
	Components: main
	Architectures: amd64
	Signed-By: /etc/apt/keyrings/brave-browser-archive-keyring.gpg
END
tryharderto sudo apt-get update
tryharderto sudo apt-get --assume-yes install brave-browser

# Mercurial settings
tee ~/.hgrc >/dev/null <<END
[extensions]
purge =
END

# Further adjust bash prompt
# Show if in flatpak
perl -pi -e 'if (/PS1/ and !/FLATPAK_ID/) { s,chroot\)\},chroot\)\}\${FLATPAK_ID+📦 \${FLATPAK_ID} }, }' ~/.bashrc
# Show git repo info
perl -pi -e 'if (/PS1/ and !/__git_ps1/) { s,\\n,\$(! type __git_ps1 &>/dev/null || __git_ps1)\\n, }' ~/.bashrc
grep --quiet 'GIT_PS1_SHOW' ~/.bashrc || tee --append ~/.bashrc >/dev/null <<END
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_HIDE_IF_PWD_IGNORED=true
export GIT_PS1_SHOWCOLORHINTS=true
END

# Git and GUI git tools settings
git config --global diff.tool kdiff3
git config --global merge.conflictstyle diff3
git config --global merge.tool kdiff3
git config --global color.ui true
git config --global rerere.enabled true
git config --global gui.editor "/usr/bin/kate"
git config --global rebase.autosquash true
# Git Cola settings. Set textwidth to help auto wrap commit messages.
git config --global cola.textwidth 70
git config --global cola.tabwidth 2
git config --global cola.linebreak true
git config --global cola.theme flat-dark-blue
git config --global cola.icontheme dark
# Arrange diff, commit, status, actions, branches, and console areas.
mkdir -p "${HOME}/.config/git-cola"
tee "${HOME}/.config/git-cola/settings" >/dev/null <<END
{
    "gui_state": {
        "mainview": {
            "geometry": "AdnQywADAAAAAAA9AAAABwAABNsAAANKAAAAPQAAACwAAATbAAADSgAAAAAAAAAABkAAAAA9AAAALAAABNsAAANK",
            "width": 1200,
            "height": 800,
            "x": 50,
            "y": 10,
            "lock_layout": false,
            "windowstate": "AAAA/wAAAAL9AAAAAQAAAAIAAASfAAADB/wBAAAAA/sAAAAIAEQAaQBmAGYBAAAAAAAAAqoAAAB1AP////wAAAKtAAAB8gAAARUA/////AIAAAAE+wAAAAwAQwBvAG0AbQBpAHQBAAAAGAAAALsAAABFAP////sAAAAMAFMAdABhAHQAdQBzAQAAANYAAAEKAAAARQD////7AAAADgBBAGMAdABpAG8AbgBzAQAAAeMAAABFAAAARQD////8AAACKwAAAPQAAABFAP////wBAAAAAvsAAAAQAEIAcgBhAG4AYwBoAGUAcwEAAAKtAAAA7AAAAKIA////+wAAAA4AQwBvAG4AcwBvAGwAZQEAAAOcAAABAwAAAHAA/////AAAAqYAAAH5AAAAAAD////6/////wEAAAAD+wAAABQAUwB1AGIAbQBvAGQAdQBsAGUAcwAAAAAA/////wAAALgA////+wAAABIARgBhAHYAbwByAGkAdABlAHMAAAAAAP////8AAAC2AP////sAAAAMAFIAZQBjAGUAbgB0AAAAAAD/////AAAAkgD///8AAASfAAAAAAAAAAQAAAAEAAAACAAAAAj8AAAAAA=="
        }
    }
}
END
# gitk solarized dark colour scheme
mkdir -p "${HOME}/.config/git"
tee "${HOME}/.config/git/gitk" >/dev/null <<END
set mainfont {sans 9}
set textfont {monospace 9}
set uifont {sans 9 bold}
set tabstop 8
set findmergefiles 0
set maxgraphpct 50
set maxwidth 16
set cmitmode patch
set wrapcomment none
set autoselect 1
set autosellen 40
set showneartags 1
set maxrefs 20
set visiblerefs {"master"}
set hideremotes 0
set showlocalchanges 1
set datetimeformat {%Y-%m-%d %H:%M:%S}
set limitdiffs 1
set uicolor #657b83
set want_ttk 1
set bgcolor #002b36
set fgcolor #839496
set uifgcolor #839496
set uifgdisabledcolor #586e75
set colors {"#6c71c4" "#268bd2" "#2aa198" "#859900" "#b58900" "#cb4b16" "#dc322f" "#d33682"}
set diffcolors {"#dc322f" "#859900" "#268bd2"}
set mergecolors {"#dc322f" "#268bd2" "#859900" "#6c71c4" brown "#009090" #d33682 "#808000" "#009000" "#ff0080" "#2aa198" "#b07070" "#70b0f0" "#70f0b0" "#f0b070" "#ff70b0"}
set markbgcolor #073642
set diffcontext 3
set selectbgcolor #073642
set foundbgcolor #b58900
set currentsearchhitbgcolor #cb4b16
set extdifftool kdiff3
set perfile_attrs 0
set headbgcolor #2aa198
set headfgcolor #002b36
set headoutlinecolor #839496
set remotebgcolor #6c71c4
set tagbgcolor #d33682
set tagfgcolor #002b36
set tagoutlinecolor #002b36
set reflinecolor #839496
set filesepbgcolor #073642
set filesepfgcolor #93a1a1
set linehoverbgcolor #073642
set linehoverfgcolor #93a1a1
set linehoveroutlinecolor #839496
set mainheadcirclecolor #fdf6e3
set workingfilescirclecolor #dc322f
set indexcirclecolor #859900
set circlecolors {white #268bd2 gray #268bd2 #268bd2}
set linkfgcolor #268bd2
set circleoutlinecolor #073642
set diffbgcolors {"#073642" "#073642"}
set web_browser xdg-open
set geometry(main) 1227x739+53+11
set geometry(state) normal
set geometry(topwidth) 1227
set geometry(topheight) 425
set geometry(pwsash0) "684 1"
set geometry(pwsash1) "1046 1"
set geometry(botwidth) 773
set geometry(botheight) 309
set permviews {}
END

# Trim Byobu status display (more thorough than `byobu-quiet`).
# Launch Byobu first to create its default configuration files.
(nohup byobu &>/dev/null &)
sleep 5s
perl -pi -e '/^(tmux_left|tmux_right)/ and s/ ([a-z])/ #\1/g' ~/.config/byobu/status

# SF Development machine setup
# ------------------------------------

TOOLSDIR="${HOME}/Desktop"

OUTPUTFILE="${TOOLSDIR}/sf-git-cola.desktop"
tee "${OUTPUTFILE}" >/dev/null <<ENDOFOUTPUTFILE
#!/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=bash -c 'cd \${HOME}/code/web-xforge && git cola'
Name=SF Git Cola Commit Tool
Icon=/usr/share/icons/hicolor/scalable/apps/git-cola.svg
ENDOFOUTPUTFILE
chmod +x "${OUTPUTFILE}"

OUTPUTFILE="${TOOLSDIR}/sf-gitk.desktop"
tee "${OUTPUTFILE}" >/dev/null <<ENDOFOUTPUTFILE
#!/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=bash -c 'cd \${HOME}/code/web-xforge && gitk --branches origin/master origin/develop origin/sf-qa origin/sf-live HEAD'
Name=SF Git History Viewer
Icon=/usr/share/git-gui/lib/git-gui.ico
ENDOFOUTPUTFILE
chmod +x "${OUTPUTFILE}"

# Panel launchers
PANEL_CONFIG=plasma-org.kde.plasma.desktop-appletsrc
ICONTASKS=5 # Task bar
kwriteconfig5 --file "${PANEL_CONFIG}" \
  --group 'Containments' --group '2' --group 'Applets' --group "${ICONTASKS}" \
  --group 'Configuration' --group 'General' --key launchers \
  'applications:chromium_chromium.desktop,applications:google-chrome.desktop,applications:microsoft-edge.desktop,applications:brave-browser.desktop,applications:firefox_firefox.desktop,preferred://filemanager,applications:org.kde.konsole.desktop'

## SF repo and dev dependencies setup

tryharderto sudo apt-get --assume-yes install ansible git

mkdir --parents ~/code
ln --symbolic --no-target-directory --force code ~/src
cd ~/code
if [ ! -d "web-xforge" ]; then
  git clone --branch ${XF_BRANCH-master} https://github.com/sillsdev/web-xforge.git
  cd web-xforge
  git config --add remote.origin.fetch +refs/notes/*:refs/notes/*
else
  cd web-xforge
  git pull --ff-only
fi

cd ~/code/web-xforge/deploy/
ansible-playbook dev-server.playbook.yml --limit localhost --diff

# Prevent npm @angular/cli from stopping to ask if we want to feed their analytics
export NG_CLI_ANALYTICS=false
# Download dependencies so VSCode doesn't show errors on start, like missing jest
cd ~/code/web-xforge && dotnet tool restore
# (Help npm not potentially stall.)
npm_maxsockets="$(npm config get maxsockets)"
npm config set maxsockets 1
cd ~/code/web-xforge/src/RealtimeServer && npm ci
cd ~/code/web-xforge/src/SIL.XForge.Scripture/ClientApp && npm ci
npm config set maxsockets "${npm_maxsockets}"
cd ~/code/web-xforge && dotnet build

# Clean up
cd ~/code/web-xforge && find test src -name obj -print0 | xargs -0 rm -vrf
cd ~/code/web-xforge && dotnet clean
# Undo temporary changes and/or clean up
cd ~/code/web-xforge && git checkout -- .config/dotnet-tools.json

# Create readme
sudo tee ~/Desktop/machine-instructions.txt >/dev/null <<END
Scripture Forge Testing and Development Machine

Automatic OS security updates are turned off (so they don't get scrambled by
switching off the guest). Install security and other updates since the
basebox was created by running the following. Try again in a few minutes if
the system is already busy fetching updates in the background. You can run
this command now and then to install security updates.

  sudo apt update && sudo apt dist-upgrade

The vagrant password is "vagrant".

See the xForge Project Workflow gdoc for setting developer secrets,
Paratext account setup, enabling multiple monitors in VirtualBox, etc.

SF is cloned in ~/code/web-xforge .

You may find it helpful to increase the amount of RAM your virtual machine
is given. To do this, run the following in your host (not this guest vagrant).
Log out and back in to your host and start the vagrant guest again.

  tee --append ~/.config/environment.d/vagrant.conf <<< "SFDEV_RAM=16000"

Development tools can optionally be installed by running the following.

  bash ~/provision-dev.sh

If you will use this machine for development,
verify that your git author info was copied in from your
host machine by printing the values with the
following commands.

  git config --get user.name
  git config --get user.email

If not correct, run

  git config --global user.name "My Name"
  git config --global user.email "me@example.com"
END

# Create canary
tee ~/Desktop/WARNING-NOT-PROVISIONED.txt >/dev/null <<END
This vagrant virtual machine did not finish provisioning correctly.

Backup any data that you want to keep from this virtual machine.
Then destroy and re-create this vagrant virtual machine by running
these commands from your host:

    vagrant destroy
    vagrant up
END

# Apply any updates
tryharderto sudo apt-get update
tryharderto sudo apt-get --assume-yes upgrade
tryharderto sudo apt-get --assume-yes dist-upgrade
# Apply grub changes, if not already done
sudo update-grub

echo "$0: $(date -Is): Script finished successfully."
