using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using MongoDB.Bson;
using Serval.Client;
using SIL.XForge.Configuration;
using SIL.XForge.DataAccess;
using SIL.XForge.Models;

namespace SIL.XForge.Scripture.Services;

/// <summary>
/// The background service that polls Serval for completed builds.
/// </summary>
public class MachineBackgroundService(
    IOptions<SiteOptions> options,
    ILogger<MachineBackgroundService> logger,
    IServiceProvider services
) : BackgroundService
{
    /// <inheritdoc />
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        // Create a scope to use services, and get required services
        using var scope = services.CreateScope();
        IExceptionHandler exceptionHandler = scope.ServiceProvider.GetRequiredService<IExceptionHandler>();
        ITranslationBuildsClient translationBuildsClient =
            scope.ServiceProvider.GetRequiredService<ITranslationBuildsClient>();
        IMachineApiService machineApiService = scope.ServiceProvider.GetRequiredService<IMachineApiService>();
        IRepository<SiteConfig> siteConfigs = scope.ServiceProvider.GetRequiredService<IRepository<SiteConfig>>();
        SiteConfig? siteConfig = null;

        // Get the site name from SiteOptions configuration
        string siteName = options.Value.Id;

        // Track the number of consecutive failures for the retry backoff
        int consecutiveFailures = 0;

        // Poll for the latest build, then process it
        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                // If we do not have it already, load the site_config document by name, creating a new one if missing
                siteConfig ??= await siteConfigs.Query().FirstOrDefaultAsync(s => s.Name == siteName, stoppingToken);
                if (siteConfig is null)
                {
                    siteConfig = new SiteConfig { Id = ObjectId.GenerateNewId().ToString(), Name = siteName };
                    await siteConfigs.InsertAsync(siteConfig, stoppingToken);
                }

                // Poll for the latest build
                TranslationBuild build = await translationBuildsClient.GetNextFinishedBuildAsync(
                    siteConfig.LastFinishedBuildId,
                    stoppingToken
                );
                if (stoppingToken.IsCancellationRequested)
                    break;

                // Process the build using the machine API, which will schedule hangfire jobs to update the drafts stored in Mongo
                await machineApiService.ProcessBuildAsync(build.Engine.Id, build.Id, build.State, stoppingToken);

                // Create/Replace the site_config document.
                // On failure throw an exception, so the next iteration of the loop will begin.
                // This is OK, as we will record the last build finished on the next iteration of the loop
                siteConfig.LastFinishedBuildId = build.Id;
                await siteConfigs.UpdateAsync(
                    siteConfig.Id,
                    u => u.Set(sc => sc.LastFinishedBuildId, build.Id),
                    cancellationToken: stoppingToken
                );

                // Reset the consecutive failure count
                consecutiveFailures = 0;
            }
            catch (ServalApiException e) when (e.StatusCode == StatusCodes.Status408RequestTimeout)
            {
                // The polling has expired (currently 40 seconds on Serval)
            }
            catch (TaskCanceledException e) when (e.InnerException is not TimeoutException)
            {
                // Exclude TaskCanceledException with an inner TimeoutException, as this generated by an HttpClient timeout
                logger.LogError(e, "Task canceled in {ServiceName}", nameof(MachineBackgroundService));
                break;
            }
            catch (Exception e)
            {
                // Log the exception, and wait with a linear stepped backoff
                // These exceptions will include errors communicating with Serval or MongoDB
                exceptionHandler.ReportException(e);

                // If the task is being canceled, just log the exception and note that the task is being canceled
                if (stoppingToken.IsCancellationRequested)
                {
                    logger.LogError(
                        e,
                        "Error occurred in {ServiceName}. Task is being canceled.",
                        nameof(MachineBackgroundService)
                    );
                    break;
                }

                // Increase backoff in 10-second increments for each block of 10 failures, up to a maximum of 60 seconds
                TimeSpan delay = TimeSpan.FromSeconds(Math.Min((((++consecutiveFailures - 1) / 10) + 1) * 10, 60));

                // Log the error with the backoff retry noted
                logger.LogError(
                    e,
                    "Error occurred in {ServiceName}. Retrying in {DelaySeconds} seconds.",
                    nameof(MachineBackgroundService),
                    delay.TotalSeconds
                );

                // Delay the next iteration of this loop, exiting the loop if the service was stopped
                try
                {
                    await Task.Delay(delay, stoppingToken);
                }
                catch (TaskCanceledException)
                {
                    break;
                }
            }
        }
    }

    /// <summary>
    /// Runs the hosted service's <see cref="ExecuteAsync"/> method.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>An asynchronous task.</returns>
    /// <remarks>This is for unit testing only. You must cancel the token to stop this method.</remarks>
    internal Task RunExecuteAsync(CancellationToken cancellationToken) => ExecuteAsync(cancellationToken);
}
