minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeExclude:
  - uuid@11.1.1
  - js-yaml@3.15.0
  - brace-expansion@2.1.2
  - brace-expansion@1.1.16
  - js-yaml@4.3.0
  - body-parser@1.20.6
  - fast-uri@3.1.4
  - fast-uri@3.1.3
