#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run npx in ClientApp.
cd src/SIL.XForge.Scripture/ClientApp
# But specify a working directory to lint-staged to work from the root of the repository.
npx --no-install lint-staged --cwd ../../..
