---
flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: project-
        type: project
        target: auto
        threshold: 1%
        informational: true
      - name_prefix: patch-
        type: patch
        target: 90%
        informational: true
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "src/SIL.XForge.Scripture/**/*.cshtml"
