#!/bin/bash
# Build for running on another computer.
# Usage: ./build-production
# May require adding <RuntimeIdentifier>linux-x64</RuntimeIdentifier> to SIL.XForge.Scripture.csproj.

set -u

scriptDir="$(dirname "$0")"
cd "${scriptDir}"
# Derive the name of the program from the name of the directory of the script.
programName="$(basename "$(pwd)")"
outputProductName="${programName}"
outputDir="bin/${outputProductName}"

grep 'RuntimeIdentifier' ../../SIL.XForge.Scripture/SIL.XForge.Scripture.csproj >/dev/null ||
  read -p "Warning: Add '<RuntimeIdentifier>linux-x64</RuntimeIdentifier>' to ../../SIL.XForge.Scripture/SIL.XForge.Scripture before continuing. Then press Enter."

dotnet publish --runtime "linux-x64" --self-contained true --output "${outputDir}" || echo "Warning: Non-zero exit code."
ls -ld "${outputDir}"
