#!/bin/bash
# Build for running on another computer.
# This is turning into a bit of a kludge, in order for the product filename to contain the date,
# the contents to be contained within a top-level folder, and not leave old intermediate production
# files laying around. But it works.
#
# Usage: ./build-production
#
# To run product on another computer:
# Set ASPNETCORE_ENVIRONMENT to Development on a workstation, Staging for QA, or omit it for Live.
# Set PTDASYNCALL_MODE to "sync" to do a sync, or anything else or omit to just inspect.
# Extract program:
#   tar xf ptda-sync-all-*.tar.xz
# Run:
#   ASPNETCORE_ENVIRONMENT=Development PTDASYNCALL_MODE="sync" SF_APP_DIR="/path/to/sf/app" \
#     ptda-sync-all-*/PtdaSyncAll |& tee /tmp/ptda.log

set -ue -o pipefail

outputProductName="ptda-sync-all-$(date '+%Y%m%d%H%M%S')"
outputDir="bin/${outputProductName}"
dotnet publish --runtime "linux-x64" -o "${outputDir}"
package="$(mktemp -d)/${outputProductName}.tar.xz"
cd "${outputDir}/.."
tar cfJ "${package}" ${outputProductName}
cd -
rm -rf "${outputDir}"
echo Product: ${package}
