#!/bin/bash
# Build for running on another computer.
#
# Usage: ./build-production
#
# To run product on another computer:
# Set ASPNETCORE_ENVIRONMENT to "Development" on a workstation, "Staging" on QA, or omit it for Live.
# Set PTDDCLONEALL_MODE to "clone" to do the clone, or omit to just inspect
# Extract program:
#   tar xf ptdd-clone-all-*.tar.xz
# Run:
#   ASPNETCORE_ENVIRONMENT="Development" PTDDCLONEALL_MODE="clone" SF_APP_DIR="/path/to/sf/app" \
#     ptdd-clone-all-*/PTDDCloneAll |& tee /tmp/ptdd.log

set -ue -o pipefail

outputProductName="ptdd-clone-all-$(date '+%Y%m%d%H%M%S')"
outputDir="bin/${outputProductName}"
dotnet publish --runtime "linux-x64" -o "${outputDir}"
package="$(mktemp -d)/${outputProductName}.tar.xz"
cd "${outputDir}/.."
tar cfJ "${package}" ${outputProductName}
echo "Product: ${package}"
