# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "marksvc/sfdev"
  config.vm.hostname = "sfdev"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.cpus = 4
    # At least 3000 MB of RAM is needed to run tests. Using an initial value here of 6000 MB in case the machine is
    # opened on a computer with 8 GB RAM. Most of the time, 14000 MB RAM is enough for development, using Code,
    # Chromium, running tests, etc. at the same time. Though more, such as 24000, is sometimes needed.
    # To set how much RAM the vagrant guest should use, you can set the RAM value in a SFDEV_RAM
    # environment variable by running a command such as
    #   tee --append ~/.config/environment.d/vagrant.conf <<< "SFDEV_RAM=14000"
    # and then logging back into your computer. Or temporarily set the value here.
    vb.memory = ENV['SFDEV_RAM'] || "6000"
    # Enable 3D acceleration and more video RAM for larger displays.
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
  end

  config.vm.provision "shell", privileged: false, inline: <<~SHELL
    set -xueo pipefail

    # Set git user and email from host.
    GIT_USER="#{`git config --get user.name`.strip}"
    GIT_EMAIL="#{`git config --get user.email`.strip}"
    [[ -z $GIT_USER ]] || git config --global user.name "${GIT_USER}"
    [[ -z $GIT_EMAIL ]] || git config --global user.email "${GIT_EMAIL}"

    cd ~/code/web-xforge
    sudo npm install --global npm@11.11.0

    sudo apt-get update
    sudo apt-get install --assume-yes dotnet-sdk-10.0

    # Remove canary
    rm -f ~/Desktop/WARNING-NOT-PROVISIONED.txt
    echo "Provisioning finished successfully."
  SHELL
end
