/* tslint:disable:ordered-imports max-line-length */
// ----------------------
// <auto-generated>
//    Generated using CodeGenerator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from SIL.XForge.Scripture.Models.SFProject
// </auto-generated>
// ----------------------

import { DomainModelConfig } from 'xforge-common/models/domain-model';
import { SFProjectRef, SFProjectUserRef } from './sfdomain-model.generated';
import { SFProject } from './sfproject';
import { SFProjectUser } from './sfproject-user';
import { QuestionsDoc } from './questions-doc';
import { TextDoc } from './text-doc';
import { CommentsDoc } from './comments-doc';
import { SFProjectDataDoc } from './sfproject-data-doc';

// All resource, resource ref, and realtime doc types should be added to schema and generated into this config
export const SFDOMAIN_MODEL_CONFIG: DomainModelConfig = {
  resourceTypes: [SFProject, SFProjectUser],
  resourceRefTypes: [SFProjectRef, SFProjectUserRef],
  realtimeDocTypes: [QuestionsDoc, TextDoc, CommentsDoc, SFProjectDataDoc]
};
