---
- name: Linux Xenial local webserver for xForge v2 developers
  hosts: all
  become: yes
  tasks: []

- import_playbook: dependencies.yml
  vars:
    config: palaso

- import_playbook: mongodb_reset.yml
