# Configuration for Windows and support for Visual Studio's Fast Mode
services:
  app:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/vscode/.microsoft/usersecrets:ro
    environment:
      - staticWebAssets=DISABLED
