import cloneDeep from 'lodash-es/cloneDeep';
import Parchment from 'parchment';
import Quill, { Clipboard, DeltaOperation, DeltaStatic, History, HistoryStackType } from 'quill';

// Generated by running
// curl -s https://raw.githubusercontent.com/ubsicap/usfm/master/sty/usfm.sty | grep '^\\Name ' | cut -c7-
// | grep -v OBSOLETE | sed 's/^DEPRECATED //g' | sed 's/\.\.\.[[:alnum:]]\{1,\}\*//g'
const USX_STYLE_DESCRIPTIONS = `id - File - Identification
usfm - File - USFM Version ID
ide - File - Encoding
h - File - Header
h1 - File - Header
h2 - File - Left Header
h3 - File - Right Header
toc1 - File - Long Table of Contents Text
toc2 - File - Short Table of Contents Text
toc3 - File - Book Abbreviation
toca1 - File - Alternative Language Long Table of Contents Text
toca2 - File - Alternative Language Short Table of Contents Text
toca3 - File - Alternative Language Book Abbreviation
rem - File - Remark
sts - File - Status
restore - File - Restore Information
imt - Introduction - Major Title Level 1
imt1 - Introduction - Major Title Level 1
imt2 - Introduction - Major Title Level 2
imt3 - Introduction - Major Title Level 3
imt4 - Introduction - Major Title Level 4
imte - Introduction - [Uncommon] Major Title at Introduction End Level 1
imte1 - Introduction - [Uncommon] Major Title at Introduction End Level 1
imte2 - Introduction - [Uncommon] Major Title at Introduction End Level 2
is - Introduction - Section Heading Level 1
is1 - Introduction - Section Heading Level 1
is2 - Introduction - Section Heading Level 2
iot - Introduction - Outline Title
io - Introduction - Outline Level 1
io1 - Introduction - Outline Level 1
io2 - Introduction - Outline Level 2
io3 - Introduction - Outline Level 3
io4 - Introduction - Outline Level 4
ior - Introduction - Outline References Range
ip - Introduction - Paragraph
im - Introduction - Paragraph - no first line indent
ipi - Introduction - Indented Para - first line indent
imi - Introduction - Indented Para - no first line indent
ili - Introduction - List Entry - Level 1
ili1 - Introduction - List Entry - Level 1
ili2 - Introduction - List Entry - Level 2
ipq - Introduction - Paragraph - quote from text
imq - Introduction - Paragraph - quote from text - no first line indent
ipr - Introduction - Paragraph - right aligned
ib - Introduction - Blank Line
iq - Introduction - Poetry Level 1
iq1 - Introduction - Poetry Level 1
iq2 - Introduction - Poetry Level 2
iq3 - Introduction - Poetry Level 3
iex - Introduction - Explanatory or Bridge Text
iqt - Special Text - Quoted Scripture Text in Introduction
ie - Introduction - End Marker
c - Chapter Number
ca - Chapter Number - Alternate
cp - Chapter Number - Publishing Alternate
cl - Chapter - Publishing Label
cd - Chapter - Description
v - Verse Number
va - Verse Number - Alternate
vp - Verse Number - Publishing Alternate
p - Paragraph - Normal - First Line Indent
m - Paragraph - Margin - No First Line Indent
po - Paragraph - Letter Opening
pr - Paragraph - Text Refrain (right aligned)
cls - Paragraph - Letter Closing
pmo - Paragraph - Embedded Text Opening
pm - Paragraph - Embedded Text
pmc - Paragraph - Embedded Text Closing
pmr - Paragraph - Embedded Text Refrain
pi - Paragraph - Indented - Level 1 - First Line Indent
pi1 - Paragraph - Indented - Level 1 - First Line Indent
pi2 - Paragraph - Indented - Level 2 - First Line Indent
pi3 - Paragraph - Indented - Level 3 - First Line Indent
pc - Paragraph - Centered (for Inscription)
mi - Paragraph - Indented - No First Line Indent
nb - Paragraph - No Break with Previous Paragraph
q - Poetry - Indent Level 1 - Single Level Only
q1 - Poetry - Indent Level 1
q2 - Poetry - Indent Level 2
q3 - Poetry - Indent Level 3
q4 - Poetry - Indent Level 4
qc - Poetry - Centered
qr - Poetry - Right Aligned
qs - Poetry Text - Selah
qa - Poetry - Acrostic Heading/Marker
qac - Poetry Text - Acrostic Letter
qm - Poetry - Embedded Text - Indent Level 1 - Single Level Only
qm1 - Poetry - Embedded Text - Indent Level 1
qm2 - Poetry - Embedded Text - Indent Level 2
qm3 - Poetry - Embedded Text - Indent Level 3
qd - Poetry - Hebrew Note
b - Poetry - Stanza Break (Blank Line)
mt - Title - Major Title Level 1
mt1 - Title - Major Title Level 1
mt2 - Title - Major Title Level 2
mt3 - Title - Major Title Level 3
mt4 - Title - Major Title level 4
mte - Title - [Uncommon] Major Title Ending Level 1
mte1 - Title - [Uncommon] Major Title Ending Level 1
mte2 - Title - [Uncommon] Major Title Ending Level 2
ms - Heading - Major Section Level 1
ms1 - Heading - Major Section Level 1
ms2 - Heading - Major Section Level 2
ms3 - Heading - Major Section Level 3
mr - Heading - Major Section Range References
s - Heading - Section Level 1
s1 - Heading - Section Level 1
s2 - Heading - Section Level 2
s3 - Heading - Section Level 3
s4 - Heading - Section Level 4
sr - Heading - Section Range References
r - Heading - Parallel References
sp - Label - Speaker
d - Label - Descriptive Title - Hebrew Subtitle
sd - Label - Semantic Division Location - Level 1
sd1 - Label - Semantic Division Location - Level 1
sd2 - Label - Semantic Division Location - Level 2
sd3 - Label - Semantic Division Location - Level 3
sd4 - Label - Semantic Division Location - Level 4
tr - Table - Row
th1 - Table - Column 1 Heading
th2 - Table - Column 2 Heading
th3 - Table - Column 3 Heading
th4 - Table - Column 4 Heading
th5 - Table - Column 5 Heading
tc1 - Table - Column 1 Cell
tc2 - Table - Column 2 Cell
tc3 - Table - Column 3 Cell
tc4 - Table - Column 4 Cell
tc5 - Table - Column 5 Cell
thc1 - Table - Column 1 Heading - Center Aligned
thc2 - Table - Column 2 Heading - Center Aligned
thc3 - Table - Column 3 Heading - Center Aligned
thc4 - Table - Column 4 Heading - Center Aligned
thc5 - Table - Column 5 Heading - Center Aligned
tcc1 - Table - Column 1 Cell - Center Aligned
tcc2 - Table - Column 2 Cell - Center Aligned
tcc3 - Table - Column 3 Cell - Center Aligned
tcc4 - Table - Column 4 Cell - Center Aligned
tcc5 - Table - Column 5 Cell - Center Aligned
thr1 - Table - Column 1 Heading - Right Aligned
thr2 - Table - Column 2 Heading - Right Aligned
thr3 - Table - Column 3 Heading - Right Aligned
thr4 - Table - Column 4 Heading - Right Aligned
thr5 - Table - Column 5 Heading - Right Aligned
tcr1 - Table - Column 1 Cell - Right Aligned
tcr2 - Table - Column 2 Cell - Right Aligned
tcr3 - Table - Column 3 Cell - Right Aligned
tcr4 - Table - Column 4 Cell - Right Aligned
tcr5 - Table - Column 5 Cell - Right Aligned
lh - List Header
li - List Entry - Level 1
li1 - List Entry - Level 1
li2 - List Entry - Level 2
li3 - List Entry - Level 3
li4 - List Entry - Level 4
lf - List Footer
lim - Embedded List Entry - Level 1
lim1 - Embedded List Entry - Level 1
lim2 - Embedded List Entry - Level 2
lim3 - Embedded List Item - Level 3
lim4 - Embedded List Entry - Level 4
litl - List Entry - Total
lik - Structured List Entry - Key
liv - Structured List Entry - Value 1
liv1 - Structured List Entry - Value 1
liv2 - Structured List Entry - Value 2
liv3 - Structured List Entry - Value 3
liv4 - Structured List Entry - Value 4
liv5 - Structured List Entry - Value 5
f - Footnote
fe - Endnote
fr - Footnote - Reference
ft - Footnote - Text
fk - Footnote - Keyword
fq - Footnote - Quotation or Alternate Rendering
fqa - Footnote - Alternate Translation Rendering
fl - Footnote - Label Text
fw - Footnote - Witness List
fp - Footnote Paragraph Mark
fv - Footnote - Embedded Verse Number
fdc - Footnote - DC text
fm - Footnote - Additional Caller to Previous Note
x - Cross Reference
xo - Cross Reference - Origin Reference
xop - Cross Reference - Origin Reference Publishing Alternate
xt - Cross Reference - Target References
xta - Cross Reference - Target References Added Text
xk - Cross Reference - Keyword
xq - Cross Reference - Quotation
xot - Cross Reference - OT Target Refs (optional)
xnt - Cross Reference - NT Target Refs (optional)
xdc - Cross Reference - DC Target Refs
rq - Cross Reference - Inline Quotation References
qt - Special Text - Quoted Text - OT in NT
nd - Special Text - Name of Deity
tl - Special Text - Transliterated Word
dc - Special Text - Deuterocanonical/LXX Additions
bk - Special Text - Quoted book title
sig - Special Text - Author's Signature (Epistles)
pn - Special Text - Proper Name
png - Special Text - Geographic Proper Name
addpn - Special Text for Chinese
wj - Special Text - Words of Jesus
k - Special Text - Keyword
sls - Special Text - Secondary Language or Text Source
ord - Special Text - Ordinal number text portion
add - Special Text - Translational Addition
lit - Special Text - Liturgical note
no - Character - Normal Text
it - Character - Italic Text
bd - Character - Bold Text
bdit - Character - BoldItalic Text
em - Character - Emphasized Text
sc - Character - Small Caps
sup - Character - Superscript
pb - Break - Page Break
fig - Auxiliary - Figure/Illustration/Map
jmp - Link text
pro - Special Text - CJK Pronunciation
rb - Special Text - Ruby Glossing
w - Peripheral Ref - Wordlist Entry
wh - Peripheral Ref - Hebrew Wordlist Entry
wg - Peripheral Ref - Greek Wordlist Entry
wa - Peripheral Ref - Aramaic Wordlist Entry
ndx - Peripheral Ref - Subject Index Entry
periph - Peripherals - Content Division Marker
p1 - Periph - Front/Back Matter Paragraph Level 1
p2 - Periph - Front/Back Matter Paragraph Level 2
k1 - Periph - Concordance Keyword Level 1
k2 - Periph - Concordance Keyword Level 2
xtSee - Concordance and Names Index - Alternate Entry Target Reference
xtSeeAlso - Concordance and Names Index - Additional Entry Target Reference
ph - Paragraph - Hanging Indent - Level 1
ph1 - Paragraph - Hanging Indent - Level 1
ph2 - Paragraph - Hanging Indent - Level 2
ph3 - Paragraph - Hanging Indent - Level 3
phi - Paragraph - Indented - Hanging Indent
fs - Footnote - Footnote Summary
zpa-xb - Periph - Book
zpa-xc - Periph - Chapter
zpa-xv - Periph - Verse
zpa-d - Periph - Description`.split('\n');

const Delta: new () => DeltaStatic = Quill.import('delta');

function customAttributeName(key: string): string {
  return 'data-' + key;
}

function getUsxDescription(value: string) {
  const usxTag = value.split('_')[0];
  const styleDescription = USX_STYLE_DESCRIPTIONS.find(s => s.startsWith(usxTag + ' ')) || '';
  return styleDescription?.startsWith('p ') ? '' : styleDescription;
}

const USX_VALUE = '__usx_value';

function getUsxValue<T>(node: HTMLElement): T {
  return node[USX_VALUE];
}

function setUsxValue(node: HTMLElement, value: any): void {
  node[USX_VALUE] = value;
}

interface UsxStyle {
  style?: string;
}

interface Para extends UsxStyle {
  vid?: string;
  status?: string;
}

interface Chapter extends UsxStyle {
  number: number;
  altnumber?: string;
  pubnumber?: string;
  sid?: string;
  eid?: string;
}

interface Verse extends UsxStyle {
  number: string;
  altnumber?: string;
  pubnumber?: string;
  sid?: string;
  eid?: string;
}

interface Note extends UsxStyle {
  caller: string;
  closed?: string;
  category?: string;
  contents?: { ops: DeltaOperation[] };
}

interface Figure extends UsxStyle {
  alt?: string;
  file: string;
  src?: string;
  size: string;
  loc?: string;
  copy?: string;
  ref: string;
  contents?: { ops: DeltaOperation[] };
}

interface Ref {
  loc: string;
}

interface Unmatched {
  marker: string;
}

export function registerScripture(): string[] {
  const QuillClipboard = Quill.import('modules/clipboard') as typeof Clipboard;
  const QuillHistory = Quill.import('modules/history') as typeof History;
  const QuillParchment = Quill.import('parchment') as typeof Parchment;
  const Inline = Quill.import('blots/inline') as typeof Parchment.Inline;
  const Block = Quill.import('blots/block') as typeof Parchment.Block;
  const Scroll = Quill.import('blots/scroll') as typeof Parchment.Scroll;
  const Embed = Quill.import('blots/embed') as typeof Parchment.Embed;
  const BlockEmbed = Quill.import('blots/block/embed') as typeof Parchment.Embed;
  const Text = Quill.import('blots/text') as typeof Parchment.Text;

  const formats: any[] = [];

  // zero width space
  const ZWSP = '\u200b';
  // non-breaking space
  const NBSP = '\u00A0';

  /**
   * This class overrides the "value" method so that it does not normalize text to NFC. This avoids a bug where Quill
   * does not properly handle NFD data (https://github.com/quilljs/quill/issues/1976).
   */
  class NotNormalizedText extends Text {
    static value(domNode: Text): string {
      return domNode.data;
    }
  }

  class VerseEmbed extends Embed {
    static blotName = 'verse';
    static tagName = 'usx-verse';

    static create(value: Verse): Node {
      const node = super.create(value) as HTMLElement;
      // add a wbr element before the verse number, so that it allows breaking
      node.appendChild(document.createElement('wbr'));
      const containerSpan = document.createElement('span');
      const verseSpan = document.createElement('span');
      verseSpan.innerText = value.number;
      containerSpan.appendChild(verseSpan);
      node.appendChild(containerSpan);
      setUsxValue(node, value);
      return node;
    }

    static value(node: HTMLElement): Verse {
      return getUsxValue(node);
    }
  }
  formats.push(VerseEmbed);

  class BlankEmbed extends Embed {
    static blotName = 'blank';
    static tagName = 'usx-blank';

    static create(value: boolean): Node {
      const node = super.create(value) as HTMLElement;
      node.innerText = NBSP.repeat(8);
      return node;
    }

    static value(_node: HTMLElement): boolean {
      return true;
    }

    static formats(node: HTMLElement): any {
      const contentNode = node.firstElementChild;
      return contentNode != null && contentNode.textContent === NBSP ? { initial: true } : undefined;
    }

    contentNode!: HTMLElement;

    format(name: string, value: any): void {
      if (name === 'initial' && value === true) {
        this.contentNode.innerText = NBSP;
      }
      super.format(name, value);
    }
  }
  formats.push(BlankEmbed);
  formats.push('initial');

  class EmptyEmbed extends Embed {
    static blotName = 'empty';
    static tagName = 'usx-empty';

    static create(value: boolean): Node {
      const node = super.create(value) as HTMLElement;
      node.innerText = ZWSP;
      return node;
    }

    static value(_node: HTMLElement): boolean {
      return true;
    }

    static formats(node: HTMLElement): boolean {
      return EmptyEmbed.value(node);
    }

    contentNode!: HTMLElement;
  }
  formats.push(EmptyEmbed);

  class CharInline extends Inline {
    static blotName = 'char';
    static tagName = 'usx-char';

    static create(value: UsxStyle): Node {
      const node = super.create(value) as HTMLElement;
      if (value != null && value.style != null) {
        node.setAttribute(customAttributeName('style'), value.style);
        setUsxValue(node, value);
      }
      return node;
    }

    static formats(node: HTMLElement): UsxStyle {
      return CharInline.value(node);
    }

    static value(node: HTMLElement): UsxStyle {
      return getUsxValue(node);
    }

    format(name: string, value: any): void {
      const usxStyle = value as UsxStyle;
      if (name === CharInline.blotName && value != null && usxStyle.style != null) {
        const elem = this.domNode as HTMLElement;
        elem.setAttribute(customAttributeName('style'), usxStyle.style);
        setUsxValue(elem, usxStyle);
      } else {
        super.format(name, value);
      }
    }
  }
  formats.push(CharInline);

  class RefInline extends Inline {
    static blotName = 'ref';
    static tagName = 'usx-ref';

    static create(value: Ref): Node {
      const node = super.create(value) as HTMLElement;
      node.setAttribute(customAttributeName('loc'), value.loc);
      setUsxValue(node, value);
      return node;
    }

    static formats(node: HTMLElement): Ref {
      return RefInline.value(node);
    }

    static value(node: HTMLElement): Ref {
      return getUsxValue(node);
    }

    format(name: string, value: any): void {
      if (name === RefInline.blotName && value != null) {
        const ref = value as Ref;
        const elem = this.domNode as HTMLElement;
        elem.setAttribute(customAttributeName('loc'), ref.loc);
        setUsxValue(elem, ref);
      } else {
        super.format(name, value);
      }
    }
  }
  formats.push(RefInline);

  class NoteEmbed extends Embed {
    static blotName = 'note';
    static tagName = 'usx-note';

    static create(value: Note): Node {
      const node = super.create(value) as HTMLElement;
      if (value != null && value.style != null) {
        node.setAttribute(customAttributeName('style'), value.style);
      }
      node.setAttribute(customAttributeName('caller'), value.caller);
      if (value.caller !== '+' && value.caller !== '-') {
        node.innerText = value.caller;
      }
      if (value.contents != null) {
        // ignore blank embeds (checked here as non-string insert)
        node.title = value.contents.ops.reduce(
          (text, op) => (typeof op.insert === 'string' ? text + op.insert : text),
          ''
        );
      }
      setUsxValue(node, value);
      return node;
    }

    static value(node: HTMLElement): Note {
      return getUsxValue(node);
    }
  }
  formats.push(NoteEmbed);

  class OptBreakEmbed extends Embed {
    static blotName = 'optbreak';
    static tagName = 'usx-optbreak';

    static create(value: UsxStyle): Node {
      const node = super.create(value) as HTMLElement;
      node.innerHTML = '<br>';
      setUsxValue(node, value);
      return node;
    }

    static value(node: HTMLElement): UsxStyle {
      return getUsxValue(node);
    }
  }
  formats.push(OptBreakEmbed);

  class FigureEmbed extends Embed {
    static blotName = 'figure';
    static tagName = 'usx-figure';

    static create(value: Figure): Node {
      const node = super.create(value) as HTMLElement;
      node.innerHTML = '&#x1f4c8';
      const title: string[] = [];
      if (value.alt != null) {
        title.push(value.alt);
      }
      if (value.file != null) {
        title.push(value.file);
      }
      if (value.src != null) {
        title.push(value.src);
      }
      if (value.size != null) {
        title.push(value.size);
      }
      if (value.loc != null) {
        title.push(value.loc);
      }
      if (value.copy != null) {
        title.push(value.copy);
      }
      if (value.contents != null) {
        title.push(value.contents.ops.reduce((text, op) => text + op.insert, ''));
      }
      if (value.ref != null) {
        title.push(value.ref);
      }
      node.title = title.join('|');
      setUsxValue(node, value);
      return node;
    }

    static value(node: HTMLElement): Figure {
      return getUsxValue(node);
    }
  }
  formats.push(FigureEmbed);

  class UnmatchedEmbed extends Embed {
    static blotName = 'unmatched';
    static tagName = 'usx-unmatched';

    static create(value: Unmatched): Node {
      const node = super.create(value) as HTMLElement;
      node.innerText = value.marker;
      setUsxValue(node, value);
      return node;
    }

    static value(node: HTMLElement): Unmatched {
      return getUsxValue(node);
    }
  }
  formats.push(UnmatchedEmbed);

  class ParaBlock extends Block {
    static blotName = 'para';
    static tagName = 'usx-para';

    static create(value: Para): Node {
      const node = super.create(value) as HTMLElement;
      if (value != null && value.style != null) {
        node.setAttribute(customAttributeName('style'), value.style);
        setUsxValue(node, value);
      }
      return node;
    }

    static formats(node: HTMLElement): Para {
      return ParaBlock.value(node);
    }

    static value(node: HTMLElement): Para {
      return getUsxValue(node);
    }

    format(name: string, value: any): void {
      const para = value as Para;
      if (name === ParaBlock.blotName && value != null && para.style != null) {
        const elem = this.domNode as HTMLElement;
        elem.setAttribute(customAttributeName('style'), para.style);
        setUsxValue(elem, para);
      } else {
        super.format(name, value);
      }
    }
  }
  formats.push(ParaBlock);

  class ParaInline extends Inline {
    static blotName = 'para-contents';
    static tagName = 'usx-para-contents';

    static value(_node: HTMLElement): boolean {
      return true;
    }

    static formats(node: HTMLElement): boolean {
      return ParaInline.value(node);
    }

    formatAt(index: number, length: number, name: string, value: any): void {
      if (name === ParaInline.blotName || name === 'invalid-inline') {
        super.formatAt(index, length, name, value);
      } else {
        this.children.forEachAt(index, length, (child, offset, len) => {
          child.formatAt(offset, len, name, value);
        });
      }
    }

    insertAt(index: number, value: string, def?: any): void {
      // force verse embeds to not get inserted inside of segments
      if (value === 'verse') {
        const [child, offset] = this.children.find(index);
        if (child != null) {
          const after = child.split(offset);
          const node = VerseEmbed.create(def);
          const blot = new VerseEmbed(node);
          this.insertBefore(blot, after);
          return;
        }
      }
      super.insertAt(index, value, def);
    }
  }
  formats.push(ParaInline);

  class SegmentInline extends Inline {
    static blotName = 'segment';
    static tagName = 'usx-segment';

    static create(value: string): Node {
      const node = super.create(value) as HTMLElement;
      node.setAttribute(customAttributeName('segment'), value);
      const styleDescription = getUsxDescription(value);
      if (styleDescription) {
        node.setAttribute(customAttributeName('style-description'), styleDescription);
      }
      return node;
    }

    static formats(node: HTMLElement): string {
      return SegmentInline.value(node);
    }

    static value(node: HTMLElement): string {
      return node.getAttribute(customAttributeName('segment'))!;
    }

    format(name: string, value: any): void {
      if (name === SegmentInline.blotName && value != null) {
        this.domNode.setAttribute(customAttributeName('segment'), value);
        const styleDescription = getUsxDescription(value);
        if (styleDescription) {
          this.domNode.setAttribute(customAttributeName('style-description'), styleDescription);
        }
      } else {
        super.format(name, value);
      }
    }
  }
  formats.push(SegmentInline);

  (Inline as any).order.push('segment');
  (Inline as any).order.push('para-contents');

  class ChapterEmbed extends BlockEmbed {
    static blotName = 'chapter';
    static tagName = 'usx-chapter';

    static create(value: Chapter): Node {
      const node = super.create(value) as HTMLElement;
      const span = document.createElement('span');
      span.innerText = value.number.toString();
      node.appendChild(span);
      node.contentEditable = 'false';
      setUsxValue(node, value);
      return node;
    }

    static value(node: HTMLElement): Chapter {
      return getUsxValue(node);
    }
  }
  formats.push(ChapterEmbed);

  Scroll.allowedChildren.push(ParaBlock);
  Scroll.allowedChildren.push(ChapterEmbed);

  class ClassAttributor extends QuillParchment.Attributor.Class {
    add(node: HTMLElement, value: any): boolean {
      if (value === true) {
        this.remove(node);
        node.classList.add(this.keyName);
        return true;
      }
      return super.add(node, value);
    }

    remove(node: HTMLElement): void {
      node.classList.remove(this.keyName);
      super.remove(node);
    }

    value(node: HTMLElement): any {
      if (node.classList.contains(this.keyName)) {
        return true;
      }
      return super.value(node);
    }
  }

  const HighlightSegmentClass = new ClassAttributor('highlight-segment', 'highlight-segment', {
    scope: Parchment.Scope.INLINE
  });
  formats.push(HighlightSegmentClass);

  const HighlightParaClass = new ClassAttributor('highlight-para', 'highlight-para', {
    scope: Parchment.Scope.BLOCK
  });
  formats.push(HighlightParaClass);

  const CheckingQuestionSegmentClass = new ClassAttributor('question-segment', 'question-segment', {
    scope: Parchment.Scope.INLINE
  });
  formats.push(CheckingQuestionSegmentClass);

  const CheckingQuestionCountAttribute = new QuillParchment.Attributor.Attribute(
    'question-count',
    'data-question-count',
    {
      scope: Parchment.Scope.INLINE
    }
  );
  formats.push(CheckingQuestionCountAttribute);

  const InvalidBlockClass = new ClassAttributor('invalid-block', 'invalid-block', {
    scope: Parchment.Scope.BLOCK
  });
  formats.push(InvalidBlockClass);

  const InvalidInlineClass = new ClassAttributor('invalid-inline', 'invalid-inline', {
    scope: Parchment.Scope.INLINE
  });
  formats.push(InvalidInlineClass);

  class DisableHtmlClipboard extends QuillClipboard {
    onPaste(e: ClipboardEvent): void {
      if (e.defaultPrevented || !this.quill.isEnabled() || e.clipboardData == null) {
        return;
      }
      const range = this.quill.getSelection();
      if (range == null) {
        return;
      }
      let delta = new Delta().retain(range.index);
      const scrollTop = this.quill.scrollingContainer.scrollTop;
      this.container.focus();
      this.quill.selection.update('silent');

      let text = e.clipboardData.getData('text/plain');
      // do not allow pasting new lines
      text = text.replace(/(?:\r?\n)+/, ' ');
      setTimeout(() => {
        this.container.innerHTML = text;
        delta = delta.concat(this.convert()).delete(range.length);
        this.quill.updateContents(delta, 'user');
        // range.length contributes to delta.length()
        this.quill.setSelection(delta.length() - range.length, 'silent');
        this.quill.scrollingContainer.scrollTop = scrollTop;
        this.quill.focus();
      }, 1);
    }
  }

  class FixSelectionHistory extends QuillHistory {
    /**
     * Performs undo/redo. Override this method, so that we can fix the selection logic. This method was copied from
     * the Quill history module.
     *
     * @param {string} source The source stack type.
     * @param {string} dest The destination stack type.
     */
    change(source: HistoryStackType, dest: HistoryStackType): void {
      const delta = this.stack[source].pop();
      if (delta == null) {
        return;
      }
      this.stack[dest].push(delta);
      this.lastRecorded = 0;
      this.ignoreChange = true;
      // during undo/redo, segments can be incorrectly highlighted, so explicitly remove incorrect highlighting
      this.quill.updateContents(removeSegmentHighlight(delta[source]), 'user');
      this.ignoreChange = false;
      const index = getLastChangeIndex(delta[source]);
      this.quill.setSelection(index);
    }
  }

  /**
   * Updates delta to remove segment highlights from segments that are not explicitly highlighted
   */
  function removeSegmentHighlight(delta: DeltaStatic): DeltaStatic {
    const updatedDelta = new Delta();
    if (delta.ops != null) {
      for (const op of delta.ops) {
        const modelOp: DeltaOperation = cloneDeep(op);
        const attrs = modelOp.attributes;
        if (attrs != null && attrs['segment'] != null && attrs['highlight-segment'] == null) {
          attrs['highlight-segment'] = false;
        }
        (updatedDelta as any).push(modelOp);
      }
    }
    return updatedDelta.chop();
  }

  /**
   * Checks if the delta ends with a newline insert. This function was copied from the Quill history module.
   */
  function endsWithNewlineChange(delta: DeltaStatic): boolean {
    if (delta.ops == null) {
      return false;
    }
    const lastOp = delta.ops[delta.ops.length - 1];
    if (lastOp == null) {
      return false;
    }
    if (lastOp.insert != null) {
      return typeof lastOp.insert === 'string' && lastOp.insert.endsWith('\n');
    }
    if (lastOp.attributes != null) {
      return Object.keys(lastOp.attributes).some(function (attr) {
        return Parchment.query(attr, Parchment.Scope.BLOCK) != null;
      });
    }
    return false;
  }

  /**
   * Finds the index where the last insert/delete occurs in the delta. This function has been modified from the
   * original in the Quill history module.
   *
   * @param {DeltaStatic} delta The undo/redo delta.
   * @returns {number} The index where the last insert/delete occurs.
   */
  function getLastChangeIndex(delta: DeltaStatic): number {
    if (delta.ops == null) {
      return 0;
    }
    // skip inserted embeds when determining last edit
    let changeIndex = 0;
    let curIndex = 0;
    for (const op of delta.ops) {
      if (op.insert != null) {
        if (typeof op.insert === 'string') {
          curIndex += op.insert.length;
          changeIndex = curIndex;
        } else {
          curIndex++;
        }
      } else if (op.retain != null) {
        curIndex += op.retain;
        changeIndex = curIndex;
      }
    }
    if (endsWithNewlineChange(delta)) {
      changeIndex -= 1;
    }
    return changeIndex;
  }

  const formatNames: string[] = [];
  for (const format of formats) {
    if (typeof format === 'string') {
      formatNames.push(format);
    } else if (format.blotName != null) {
      Quill.register(`blots/${format.blotName}`, format);
      formatNames.push(format.blotName);
    } else {
      Quill.register(`formats/${format.attrName}`, format);
      formatNames.push(format.attrName);
    }
  }
  Quill.register('blots/scroll', Scroll, true);
  Quill.register('blots/text', NotNormalizedText, true);
  Quill.register('modules/clipboard', DisableHtmlClipboard, true);
  Quill.register('modules/history', FixSelectionHistory, true);

  return formatNames;
}
