// Generated by running
// curl -s https://raw.githubusercontent.com/ubsicap/usfm/master/sty/usfm.sty | grep '^\\Name ' | cut -c7-
// | grep -v OBSOLETE | sed 's/^DEPRECATED //g' | sed 's/\.\.\.[[:alnum:]]\{1,\}\*//g'
export const USFM_STYLE_DESCRIPTIONS: { [style: string]: string } = `id - File - Identification
usfm - File - USFM Version ID
ide - File - Encoding
h - File - Header
h1 - File - Header
h2 - File - Left Header
h3 - File - Right Header
toc1 - File - Long Table of Contents Text
toc2 - File - Short Table of Contents Text
toc3 - File - Book Abbreviation
toca1 - File - Alternative Language Long Table of Contents Text
toca2 - File - Alternative Language Short Table of Contents Text
toca3 - File - Alternative Language Book Abbreviation
rem - File - Remark
sts - File - Status
restore - File - Restore Information
imt - Introduction - Major Title Level 1
imt1 - Introduction - Major Title Level 1
imt2 - Introduction - Major Title Level 2
imt3 - Introduction - Major Title Level 3
imt4 - Introduction - Major Title Level 4
imte - Introduction - [Uncommon] Major Title at Introduction End Level 1
imte1 - Introduction - [Uncommon] Major Title at Introduction End Level 1
imte2 - Introduction - [Uncommon] Major Title at Introduction End Level 2
is - Introduction - Section Heading Level 1
is1 - Introduction - Section Heading Level 1
is2 - Introduction - Section Heading Level 2
iot - Introduction - Outline Title
io - Introduction - Outline Level 1
io1 - Introduction - Outline Level 1
io2 - Introduction - Outline Level 2
io3 - Introduction - Outline Level 3
io4 - Introduction - Outline Level 4
ior - Introduction - Outline References Range
ip - Introduction - Paragraph
im - Introduction - Paragraph - no first line indent
ipi - Introduction - Indented Para - first line indent
imi - Introduction - Indented Para - no first line indent
ili - Introduction - List Entry - Level 1
ili1 - Introduction - List Entry - Level 1
ili2 - Introduction - List Entry - Level 2
ipq - Introduction - Paragraph - quote from text
imq - Introduction - Paragraph - quote from text - no first line indent
ipr - Introduction - Paragraph - right aligned
ib - Introduction - Blank Line
iq - Introduction - Poetry Level 1
iq1 - Introduction - Poetry Level 1
iq2 - Introduction - Poetry Level 2
iq3 - Introduction - Poetry Level 3
iex - Introduction - Explanatory or Bridge Text
iqt - Special Text - Quoted Scripture Text in Introduction
ie - Introduction - End Marker
c - Chapter Number
ca - Chapter Number - Alternate
cp - Chapter Number - Publishing Alternate
cl - Chapter - Publishing Label
cd - Chapter - Description
v - Verse Number
va - Verse Number - Alternate
vp - Verse Number - Publishing Alternate
p - Paragraph - Normal - First Line Indent
m - Paragraph - Margin - No First Line Indent
po - Paragraph - Letter Opening
pr - Paragraph - Text Refrain (right aligned)
cls - Paragraph - Letter Closing
pmo - Paragraph - Embedded Text Opening
pm - Paragraph - Embedded Text
pmc - Paragraph - Embedded Text Closing
pmr - Paragraph - Embedded Text Refrain
pi - Paragraph - Indented - Level 1 - First Line Indent
pi1 - Paragraph - Indented - Level 1 - First Line Indent
pi2 - Paragraph - Indented - Level 2 - First Line Indent
pi3 - Paragraph - Indented - Level 3 - First Line Indent
pc - Paragraph - Centered (for Inscription)
mi - Paragraph - Indented - No First Line Indent
nb - Paragraph - No Break with Previous Paragraph
q - Poetry - Indent Level 1 - Single Level Only
q1 - Poetry - Indent Level 1
q2 - Poetry - Indent Level 2
q3 - Poetry - Indent Level 3
q4 - Poetry - Indent Level 4
qc - Poetry - Centered
qr - Poetry - Right Aligned
qs - Poetry Text - Selah
qa - Poetry - Acrostic Heading/Marker
qac - Poetry Text - Acrostic Letter
qm - Poetry - Embedded Text - Indent Level 1 - Single Level Only
qm1 - Poetry - Embedded Text - Indent Level 1
qm2 - Poetry - Embedded Text - Indent Level 2
qm3 - Poetry - Embedded Text - Indent Level 3
qd - Poetry - Hebrew Note
b - Poetry - Stanza Break (Blank Line)
mt - Title - Major Title Level 1
mt1 - Title - Major Title Level 1
mt2 - Title - Major Title Level 2
mt3 - Title - Major Title Level 3
mt4 - Title - Major Title level 4
mte - Title - [Uncommon] Major Title Ending Level 1
mte1 - Title - [Uncommon] Major Title Ending Level 1
mte2 - Title - [Uncommon] Major Title Ending Level 2
ms - Heading - Major Section Level 1
ms1 - Heading - Major Section Level 1
ms2 - Heading - Major Section Level 2
ms3 - Heading - Major Section Level 3
mr - Heading - Major Section Range References
s - Heading - Section Level 1
s1 - Heading - Section Level 1
s2 - Heading - Section Level 2
s3 - Heading - Section Level 3
s4 - Heading - Section Level 4
sr - Heading - Section Range References
r - Heading - Parallel References
sp - Label - Speaker
d - Label - Descriptive Title - Hebrew Subtitle
sd - Label - Semantic Division Location - Level 1
sd1 - Label - Semantic Division Location - Level 1
sd2 - Label - Semantic Division Location - Level 2
sd3 - Label - Semantic Division Location - Level 3
sd4 - Label - Semantic Division Location - Level 4
tr - Table - Row
th1 - Table - Column 1 Heading
th2 - Table - Column 2 Heading
th3 - Table - Column 3 Heading
th4 - Table - Column 4 Heading
th5 - Table - Column 5 Heading
tc1 - Table - Column 1 Cell
tc2 - Table - Column 2 Cell
tc3 - Table - Column 3 Cell
tc4 - Table - Column 4 Cell
tc5 - Table - Column 5 Cell
thc1 - Table - Column 1 Heading - Center Aligned
thc2 - Table - Column 2 Heading - Center Aligned
thc3 - Table - Column 3 Heading - Center Aligned
thc4 - Table - Column 4 Heading - Center Aligned
thc5 - Table - Column 5 Heading - Center Aligned
tcc1 - Table - Column 1 Cell - Center Aligned
tcc2 - Table - Column 2 Cell - Center Aligned
tcc3 - Table - Column 3 Cell - Center Aligned
tcc4 - Table - Column 4 Cell - Center Aligned
tcc5 - Table - Column 5 Cell - Center Aligned
thr1 - Table - Column 1 Heading - Right Aligned
thr2 - Table - Column 2 Heading - Right Aligned
thr3 - Table - Column 3 Heading - Right Aligned
thr4 - Table - Column 4 Heading - Right Aligned
thr5 - Table - Column 5 Heading - Right Aligned
tcr1 - Table - Column 1 Cell - Right Aligned
tcr2 - Table - Column 2 Cell - Right Aligned
tcr3 - Table - Column 3 Cell - Right Aligned
tcr4 - Table - Column 4 Cell - Right Aligned
tcr5 - Table - Column 5 Cell - Right Aligned
lh - List Header
li - List Entry - Level 1
li1 - List Entry - Level 1
li2 - List Entry - Level 2
li3 - List Entry - Level 3
li4 - List Entry - Level 4
lf - List Footer
lim - Embedded List Entry - Level 1
lim1 - Embedded List Entry - Level 1
lim2 - Embedded List Entry - Level 2
lim3 - Embedded List Item - Level 3
lim4 - Embedded List Entry - Level 4
litl - List Entry - Total
lik - Structured List Entry - Key
liv - Structured List Entry - Value 1
liv1 - Structured List Entry - Value 1
liv2 - Structured List Entry - Value 2
liv3 - Structured List Entry - Value 3
liv4 - Structured List Entry - Value 4
liv5 - Structured List Entry - Value 5
f - Footnote
fe - Endnote
fr - Footnote - Reference
ft - Footnote - Text
fk - Footnote - Keyword
fq - Footnote - Quotation or Alternate Rendering
fqa - Footnote - Alternate Translation Rendering
fl - Footnote - Label Text
fw - Footnote - Witness List
fp - Footnote Paragraph Mark
fv - Footnote - Embedded Verse Number
fdc - Footnote - DC text
fm - Footnote - Additional Caller to Previous Note
x - Cross Reference
xo - Cross Reference - Origin Reference
xop - Cross Reference - Origin Reference Publishing Alternate
xt - Cross Reference - Target References
xta - Cross Reference - Target References Added Text
xk - Cross Reference - Keyword
xq - Cross Reference - Quotation
xot - Cross Reference - OT Target Refs (optional)
xnt - Cross Reference - NT Target Refs (optional)
xdc - Cross Reference - DC Target Refs
rq - Cross Reference - Inline Quotation References
qt - Special Text - Quoted Text - OT in NT
nd - Special Text - Name of Deity
tl - Special Text - Transliterated Word
dc - Special Text - Deuterocanonical/LXX Additions
bk - Special Text - Quoted book title
sig - Special Text - Author's Signature (Epistles)
pn - Special Text - Proper Name
png - Special Text - Geographic Proper Name
addpn - Special Text for Chinese
wj - Special Text - Words of Jesus
k - Special Text - Keyword
sls - Special Text - Secondary Language or Text Source
ord - Special Text - Ordinal number text portion
add - Special Text - Translational Addition
lit - Special Text - Liturgical note
no - Character - Normal Text
it - Character - Italic Text
bd - Character - Bold Text
bdit - Character - BoldItalic Text
em - Character - Emphasized Text
sc - Character - Small Caps
sup - Character - Superscript
pb - Break - Page Break
fig - Auxiliary - Figure/Illustration/Map
jmp - Link text
pro - Special Text - CJK Pronunciation
rb - Special Text - Ruby Glossing
w - Peripheral Ref - Wordlist Entry
wh - Peripheral Ref - Hebrew Wordlist Entry
wg - Peripheral Ref - Greek Wordlist Entry
wa - Peripheral Ref - Aramaic Wordlist Entry
ndx - Peripheral Ref - Subject Index Entry
periph - Peripherals - Content Division Marker
p1 - Periph - Front/Back Matter Paragraph Level 1
p2 - Periph - Front/Back Matter Paragraph Level 2
k1 - Periph - Concordance Keyword Level 1
k2 - Periph - Concordance Keyword Level 2
xtSee - Concordance and Names Index - Alternate Entry Target Reference
xtSeeAlso - Concordance and Names Index - Additional Entry Target Reference
ph - Paragraph - Hanging Indent - Level 1
ph1 - Paragraph - Hanging Indent - Level 1
ph2 - Paragraph - Hanging Indent - Level 2
ph3 - Paragraph - Hanging Indent - Level 3
phi - Paragraph - Indented - Hanging Indent
fs - Footnote - Footnote Summary
zpa-xb - Periph - Book
zpa-xc - Periph - Chapter
zpa-xv - Periph - Verse
zpa-d - Periph - Description`
  .split('\n')
  .reduce((result: object, description: string) => {
    result[description.substring(0, description.indexOf(' '))] = description;
    return result;
  }, {});
