export const environment = {
  releaseStage: 'qa',
  pwaTest: false,
  production: true,
  beta: false,
  betaUrl: 'https://qa.beta.scriptureforge.org',
  masterUrl: 'https://qa.scriptureforge.org',
  issueEmail: 'scriptureforgeissues@sil.org',
  siteName: 'Scripture Forge',
  audience: 'https://scriptureforge.org/',
  scope: 'sf_data',
  siteId: 'sf',
  assets: '/assets/',
  helps: 'https://help.scriptureforge.org',
  bugsnagApiKey: 'b72a46a8924a3cd161d4c5534287923c',
  realtimePort: 0,
  realtimeUrl: '/realtime-api/',
  authDomain: 'dev-sillsdev.auth0.com',
  authClientId: '4eHLjo40mAEGFU6zUxdYjnpnC1K1Ydnj',
  offlineDBVersion: 5
};
