export const environment = {
  releaseStage: 'dev',
  pwaTest: true,
  production: false,
  masterUrl: 'http://localhost:5000',
  issueEmail: 'help@scriptureforge.org',
  siteName: 'Scripture Forge',
  audience: 'https://scriptureforge.org/',
  scope: 'sf_data',
  siteId: 'sf',
  assets: '/assets/',
  helps: 'https://help.scriptureforge.org',
  bugsnagApiKey: 'b72a46a8924a3cd161d4c5534287923c',
  realtimePort: 5003,
  realtimeSecurePort: 5005,
  realtimeUrl: '/',
  authDomain: 'sil-appbuilder.auth0.com',
  authClientId: 'aoAGb9Yx1H5WIsvCW6JJCteJhSa37ftH',
  offlineDBVersion: 8,
  googleTagManagerId: 'GTM-P2DF8SLM',
  googleTagManagerAuth: 'AC1M72Jw4UydK-bnFoT0Cw',
  googleTagManagerPreview: 'env-8'
};
