export const environment = {
  releaseStage: 'qa',
  pwaTest: false,
  production: true,
  masterUrl: 'https://qa.scriptureforge.org',
  issueEmail: 'help@scriptureforge.org',
  siteName: 'Scripture Forge',
  audience: 'https://scriptureforge.org/',
  scope: 'sf_data',
  siteId: 'sf',
  assets: '/assets/',
  helps: 'https://github-action-preview--scriptureforgehelp.netlify.app',
  bugsnagApiKey: 'b72a46a8924a3cd161d4c5534287923c',
  realtimePort: 0,
  realtimeSecurePort: 0,
  realtimeUrl: '/realtime-api/',
  authDomain: 'dev-sillsdev.auth0.com',
  authClientId: '4eHLjo40mAEGFU6zUxdYjnpnC1K1Ydnj',
  offlineDBVersion: 8,
  googleTagId: null
};
