export const environment = {
  releaseStage: 'dev',
  pwaTest: true,
  production: false,
  beta: false,
  betaUrl: 'http://beta.localhost:9000',
  masterUrl: 'http://localhost:5000',
  issueEmail: 'scriptureforgeissues@sil.org',
  siteName: 'Scripture Forge',
  audience: 'https://scriptureforge.org/',
  scope: 'sf_data',
  siteId: 'sf',
  assets: '/assets/',
  helps: 'https://help.scriptureforge.org',
  bugsnagApiKey: 'b72a46a8924a3cd161d4c5534287923c',
  realtimePort: 5003,
  realtimeUrl: '/',
  authDomain: 'sil-appbuilder.auth0.com',
  authClientId: 'aoAGb9Yx1H5WIsvCW6JJCteJhSa37ftH',
  offlineDBVersion: 4
};
