#!/bin/bash
#
# Build SF for Live or QA. Upload to server to deploy.

set -xueo pipefail

BUILD_OUTPUT="artifacts"
DEPLOY_PATH="/var/www/${APP_NAME}.org${APP_SUFFIX}"
SERVICE_UNIT_SUFFIX=""
# Relative to repo root
ERROR_PAGES_PATH="src/SIL.XForge.Scripture/ErrorPages"

scriptDir="$(dirname "$0")"
"${scriptDir}"/build-production "$@"

cd "${scriptDir}/.."

cat <<EOF > "$BUILD_OUTPUT/app/secrets.json"
{
  "Paratext": {
    "ClientId": "${PARATEXT_CLIENT_ID}",
    "ClientSecret": "${PARATEXT_API_TOKEN}",
    "ResourcePasswordHash": "${PARATEXT_RESOURCE_PASSWORD_HASH}",
    "ResourcePasswordBase64": "${PARATEXT_RESOURCE_PASSWORD_BASE64}"
  },
  "Auth": {
    "BackendClientSecret": "${AUTH_BACKEND_SECRET}",
    "WebhookPassword": "${AUTH_WEBHOOK_PASSWORD}"
  }
}
EOF

sudo chown -R :www-data "${BUILD_OUTPUT}/app"

rsync -progzlt --chmod=Dug=rwx,Fug=rwx,o-rwx --delete-during --stats --rsync-path="sudo rsync" \
  --rsh="ssh -v -i ${DEPLOY_CREDENTIALS}" artifacts/app/ root@"${DEPLOY_DESTINATION}:${DEPLOY_PATH}/app"

rsync -vaz --rsync-path="sudo rsync" --rsh="ssh -v -i ${DEPLOY_CREDENTIALS}" \
  "${ERROR_PAGES_PATH}/" root@"${DEPLOY_DESTINATION}:${DEPLOY_PATH}/htdocs"

ssh root@"${DEPLOY_DESTINATION}" "systemctl restart ${APP_NAME}-web-app${SERVICE_UNIT_SUFFIX}"
