version: '3.7'
services:
  scriptureforge:
    image: scriptureforge
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
    - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets
