version: '3.7'
services:
  mongodb:
    image: mongo:5.0
    command: mongod
    volumes:
      - /data/db
    networks:
      webnet:
        aliases:
          - localhost

  scriptureforge:
    depends_on:
      - 'mongodb'
    image: scriptureforge
    command: dotnet run
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets
    ports:
      - "5000:5000"
      - "5003:5003"
    networks:
      - webnet
networks:
  webnet:
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
