name: Grit check

on:
  push:
    branches: [master, develop, sf-qa, sf-live]
  pull_request:
    branches: [master, develop]

permissions: {}

jobs:
  grit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: grit-check
        uses: getgrit/github-action-check@c1ba5f99fd0e46f4cdc35d8dbc4622610ccc1784 # v0
