name: Grit check
permissions: {}

on:
  push:
    branches: [master, develop, sf-qa, sf-live]
  pull_request:
  merge_group:

jobs:
  grit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      # Install Node so npm can be used to install Grit
      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "22.13.0"

      # The following steps were copied from github.com/honeycombio/github-action-check/blob/main/action.yaml with
      # slight simplifications.
      # The install method was changed from running https://docs.grit.io/install to using npm because the install URL
      # redirects to https://github.com/biomejs/gritql/releases/download/v0.0.2/grit-installer.sh, which returns 404.
      - name: Install Grit
        run: npm install --location=global @getgrit/cli@0.1.0-alpha.1743007075
      - name: Init Grit
        run: grit init
      - name: Run Grit check
        run: grit check --github-actions
