name: "Push files to Crowdin"
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json"
      - "src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json"
      - "src/SIL.XForge.Scripture/Resources/SharedResource.resx"
      - "src/SIL.XForge.Scripture/Resources/Pages.Index.resx"
      - "src/SIL.XForge.Scripture/Resources/Pages.NotFound.resx"

jobs:
  push_files_to_crowdin:
    name: "Push files to Crowdin"
    runs-on: ubuntu-24.04
    environment: Crowdin

    steps:
      - name: "Fail if not on master"
        if: github.ref != 'refs/heads/master'
        shell: bash
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "This workflow must be run on the master branch (got '${GITHUB_REF}')."
          exit 1

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: "Set up Deno"
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: v2.x

      - name: "Push files to Crowdin"
        run: scripts/push_changes_to_crowdin.mts
        env:
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
