name: Release to QA

on:
  schedule:
    # Run on Tuesday-Sunday at 01:30 UTC, just before beginning of tester workday.
    - cron: '30 1 * * TUE-SUN'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set sf-qa to master
      run: |
        git config --global user.email "automated"
        git config --global user.name "Automated"
        git push origin origin/master:sf-qa
