name: Update Localizations

on:
  schedule:
    - cron: "0 21 * * 5" # Runs every Friday
  workflow_dispatch:

jobs:
  update-localizations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SF_PUSH_KEY }}

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run update_from_crowdin.mts
        run: scripts/update_from_crowdin.mts
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update all translation files from Crowdin
          title: Update all translation files from Crowdin
          body: Automated update of files by GitHub action
          branch: i18n/update
          base: master
