name: Update PNPM Dependencies
permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 17 * * *" # Run every day at noon Eastern Time (17:00 UTC)
  workflow_dispatch:

jobs:
  update-npm-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true

      - name: Set up pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 11.10

      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "22.13.0"
          cache: "pnpm"
          cache-dependency-path: |
            src/SIL.XForge.Scripture/ClientApp/pnpm-lock.yaml
            src/RealtimeServer/pnpm-lock.yaml
            scripts/db_tools/pnpm-lock.yaml

      - name: Run pnpm audit --fix update on RealtimeServer
        run: |
          cd src/RealtimeServer
          pnpm ci
          pnpm audit --fix update
        continue-on-error: true

      - name: Run pnpm audit --fix update on ClientApp
        run: |
          cd src/SIL.XForge.Scripture/ClientApp
          pnpm ci
          pnpm audit --fix update
        continue-on-error: true

      - name: Run pnpm audit --fix update on db_tools
        run: |
          cd scripts/db_tools
          pnpm ci
          pnpm audit --fix update
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          commit-message: Update PNPM dependencies via pnpm audit --fix update
          title: Update PNPM dependencies via pnpm audit --fix update
          body: |
            Automated update of PNPM dependencies by running `pnpm audit --fix update` on all package.json files.

            This PR was automatically created by the GitHub action.

            Please review the changes carefully before merging.
          branch: pnpm/update-dependencies
          base: master
